## [array 연산] <hr>
- 원소 단위(Element-wise) 연산
    * 같은 인덱스의 우너소끼리 연산 진행
    * 숫자와 array 사이 연산 => 숫자를 벡터화 후 연산 수행

In [3]:
import numpy as np

In [8]:
arr1d = np.array([10,20,30])
arr1 = np.array([10,20,30])
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
arr3d = np.array([[[11,22,33],[44,55,66]],
         [[77,88,99],[7,8,9]]])

In [9]:
# 기본 산술 연산
# => array와 숫자 데이터 연산
print(f'{arr1d} + 5 = {arr1d+arr1}')
print(f'{arr1d} - 5 = {arr1d-5}')
print(f'{arr1d} * 5 = {arr1d*5}')
print(f'{arr1d} // 5 = {arr1d//5}')

[10 20 30] + 5 = [20 40 60]
[10 20 30] - 5 = [ 5 15 25]
[10 20 30] * 5 = [ 50 100 150]
[10 20 30] // 5 = [2 4 6]


In [6]:
# 기본 비교 연산
# => array와 숫자 데이터 연산
print(f'{arr1d} == 5 = {arr1d == 5}')
print(f'{arr1d} != 5 = {arr1d != 5}')
print(f'{arr1d} <= 5 = {arr1d <= 5}')
print(f'{arr1d} >= 5 = {arr1d >= 5}')

[10 20 30] == 5 = [False False False]
[10 20 30] != 5 = [ True  True  True]
[10 20 30] <= 5 = [False False False]
[10 20 30] >= 5 = [ True  True  True]


In [8]:
# Numpy 제공 수학관련 함수들
print(f'{arr1d} => np.sqrt(arr1d) : {np.sqrt(arr1d)}')
print(f'{arr1d} => 로그값 : {np.log(arr1d)}')
print(f'{arr1d} => 지수값 : {np.exp(arr1d)}')
print(f'np.pi : {np.pi}')

[10 20 30] => np.sqrt(arr1d) : [3.16227766 4.47213595 5.47722558]
[10 20 30] => 로그값 : [2.30258509 2.99573227 3.40119738]
[10 20 30] => 지수값 : [2.20264658e+04 4.85165195e+08 1.06864746e+13]
np.pi : 3.141592653589793


In [ ]:
# Numpy 제공 집계 관련 함수들 => 축 axis 설정
# - axis = 0 : 열 단위 집계
# - axis = 1 : 행 단위 집계
print(arr2d)

print(f'모든 원소 합계 : {arr2d.sum()}')
print(f'열 방향 합계   : {arr2d.sum(axis=0)}')
print(f'행 방향 합계   : {arr2d.sum(axis=1)}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
모든 원소 합계 : 78
열 방향 합계   : [15 18 21 24]
행 방향 합계   : [10 26 42]


In [11]:
print(f'모든 원소 최대값 : {arr2d.max()}')
print(f'열 방향 최대값   : {arr2d.max(axis=0)}')
print(f'행 방향 최대값   : {arr2d.max(axis=1)}')

모든 원소 최대값 : 12
열 방향 최대값   : [ 9 10 11 12]
행 방향 최대값   : [ 4  8 12]


In [28]:
# 2번째 2D array에서 원소값 8 추출 => 원소 1개
arr3d[1][1][1], arr3d[1,1,1]

(np.int64(8), np.int64(8))