## [array 차원/형태 변경] <hr>
- N 차원 < --- > 1차원
    * 원소 개수 동일해야 함
    * 함 수 : np.reshape()
    * 메서드 : ndarray.reshape()

In [2]:
import numpy as np

In [35]:
arr1d = np.arange(1, 31)
arr2d = arr1d.reshape(-1, 3) # 컬럼 수 3개, 행 수는 자동
arr3d = arr1d.reshape(5, 2, -1) # 깊이/개수 5개, 행 수 2개, 컬럼 자동

print(arr2d, arr3d, sep='\n\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]


In [36]:
# reshape()으로 생성된 ndarray 특징
arr2d[0,0] = 100
arr1d[-1] = 77

# => 원본 arr1d 과 변환된 arr2d
print(arr1d, arr2d, sep='\n\n')

[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  77]

[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]
 [ 13  14  15]
 [ 16  17  18]
 [ 19  20  21]
 [ 22  23  24]
 [ 25  26  27]
 [ 28  29  77]]


In [37]:
# Nckdnjs ---> 1차원으로 변환 : 평탄화
# => reshape(-1)
arr3d.reshape(-1)

np.reshape(arr3d, -1)

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  77])

In [38]:
# => flatten()
f = arr3d.flatten()

# arr3d[0,0,1] = 200
f[1] = 200

print(arr3d, f, sep='\n\n')

[[[100   2   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ 13  14  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]]

 [[ 25  26  27]
  [ 28  29  77]]]

[100 200   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  77]


In [39]:
# => ravel()
f = arr3d.ravel()

f[2] = 300

print(arr3d, f, sep='\n\n')

[[[100   2 300]
  [  4   5   6]]

 [[  7   8   9]
  [ 10  11  12]]

 [[ 13  14  15]
  [ 16  17  18]]

 [[ 19  20  21]
  [ 22  23  24]]

 [[ 25  26  27]
  [ 28  29  77]]]

[100   2 300   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  77]


In [40]:
arr3d

array([[[100,   2, 300],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 13,  14,  15],
        [ 16,  17,  18]],

       [[ 19,  20,  21],
        [ 22,  23,  24]],

       [[ 25,  26,  27],
        [ 28,  29,  77]]])