## [array에서 원소 추출] <hr>
- 인덱스기반 원소 추출
    * 1차원 배열 : 변수명[인덱스]
    * 2차원 배열 : 변수명[행인덱스] -- 행 추출, 변수명[행인덱스, 열 인덱스], 
                                    변수명[행인덱스, 열인덱스] - 원소 추출
- 팬시 인덱싱기반 원소 추출
    * 비연속적, 비규칙적 원소 추출 시 사용
    * 행 추출 : [ 인덱스, 인덱스, ... ]
    * 원소 추출 : [행인덱스, 행인덱스], [열인덱스, 열인덱스] 
        - [행인덱스1, 열인덱스1], [행인덱스2, 열인덱스2]
    * 교차 원소 추출 : np.ix_([행인덱스1, 행인덱스2], [열인덱스1, 열인덱스2])

In [2]:
import numpy as np

In [3]:
arr = np.arange(24).reshape(2, 3, 4)  # shape (2,3,4)
# axis: 0=깊이(depth), 1=행(row), 2=열(col)
print(arr.shape)                       # 출력 1
print(arr.reshape(6, 4).shape)         # 출력 2
print(arr.reshape(2, 12).shape)        # 출력 3
print(arr.reshape(-1).shape)           # 출력 4

(2, 3, 4)
(6, 4)
(2, 12)
(24,)


In [2]:
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

In [3]:
# 행 추출
arr2d[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 특정 값 추출 => 교차 인덱스 : np.ix() 함수
arr2d[np.ix_([0,2],[1,3])]

array([[ 2,  4],
       [10, 12]])

### 3D차원 ndarray 다루기 <hr>

In [18]:
arr3d = np.array([[[11,22,33],[44,55,66]],
         [[77,88,99],[7,8,9]]])
print(arr3d.shape, arr3d.ndim, sep="\n")

(2, 2, 3)
3


In [ ]:
# 2번째 2D array 추출
arr3d[1]

array([[77, 88, 99],
       [ 7,  8,  9]])

In [25]:
# 2번째 2D array에서 1번 행 추출 => 1D
arr3d[1][1]

array([7, 8, 9])

In [28]:
# 2번째 2D array에서 원소값 8 추출 => 원소 1개
arr3d[1][1][1], arr3d[1,1,1]

(np.int64(8), np.int64(8))