## [행렬 곱셈] <hr>
- 내적연산 : 차원유지, 행과 열 원소 곱한 후 덧셈 처리
    * 함수 : np.dot(arr1, arr2), np.matmul(arr1, arr2)
    * 연산자 : @
    * 조건 : 앞에 array의 열 개수 == 뒤에 array의 행 개수
- 외적연산 : 새로운 차원의 ndarray 생성, 모든 요소 조합으로 생성
    * np.outer(arr1, arr2)

In [2]:
import numpy as np

In [6]:
a1 = np.arange(1, 9).reshape(2,4)
a2 = np.arange(1, 5).reshape(4,-1)
a3 = np.arange(1, 5).reshape(1,4)

print(a1.shape, a2.shape, a3.shape)
print(f'{a1} \n {a2} \n {a3}')

(2, 4) (4, 1) (1, 4)
[[1 2 3 4]
 [5 6 7 8]] 
 [[1]
 [2]
 [3]
 [4]] 
 [[1 2 3 4]]


In [12]:
# 행렬 내적 연산 - (1) np.matmul()
a12 = np.matmul(a1,a2) # (2,4) (4,1)
print(a12)

a13 = np.matmul(a1,a3.T) # (2,4) (1,4)
print(a13)

op = a1 @ a2
print(op)

[[30]
 [70]]
[[30]
 [70]]
[[30]
 [70]]


In [23]:
# 행렬 외적 연산 - (2) np.outer()
a12 = np.outer(a1,a2)
print(a12)

a13 = np.outer(a1,a3)
print(a13)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]
