## [ 정렬 & arg 함수명() ] <hr>
- 함수 : np.sort() => [기] 오름차순 정렬된 ndarray 반환
- 메서드 : ndarray.sort() => 원본 정렬됨

- argOOO() 함수들
    - 해당 값이 있는 인덱스를 반환
    - 예 : ndarray.max() - 원소 중 가장 큰 값, ndarray.argmax() : 원소 중 가장 큰 값의 인덱스

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0], arr[-1], arr[1:4])

10 50 [20 30 40]


In [3]:
a1 = np.array([[3,1,6],
               [0,7,4],
               [5,3,2]])

In [4]:
# 정렬
## 함수 : np.sort()
as1 = np.sort(a1, axis=None)
print("정렬 전 ==>", a1.shape , a1 )
print("정렬 후 ==>\n", as1, end='\n\n')

as1 = np.sort(a1, axis=0)
print("행 기준 정렬 후 ==>\n",  as1, end='\n\n')

as1 = np.sort(a1, axis=1)
print("열 기준 정렬 후 ==>\n",  as1, end='\n\n')

정렬 전 ==> (3, 3) [[3 1 6]
 [0 7 4]
 [5 3 2]]
정렬 후 ==>
 [0 1 2 3 3 4 5 6 7]

행 기준 정렬 후 ==>
 [[0 1 2]
 [3 3 4]
 [5 7 6]]

열 기준 정렬 후 ==>
 [[1 3 6]
 [0 4 7]
 [2 3 5]]



In [5]:
## 메서드 : ndarray.sort() 원본 변경됨 
##         [기] axis=-1  : -1번 축 기준 오름차순 정렬 
print("정렬 전 ==>", a1 )

## -1번 축 기준 오름차순 정렬 즉, 행방향 정렬
a1.sort()
print("a1  ==>", a1 )

## 열방향 정렬
a1.sort(axis=0)
print("a1  ==>", a1 )

정렬 전 ==> [[3 1 6]
 [0 7 4]
 [5 3 2]]
a1  ==> [[1 3 6]
 [0 4 7]
 [2 3 5]]
a1  ==> [[0 3 5]
 [1 3 6]
 [2 4 7]]


In [6]:
# argsort() : 정렬 전 데이터가 있는 인덱스 반환
a1 = np.array([ [3,	1,	6],	
		        [0,	7,	4],	
		        [5,	3,	2]])

arr_idx = np.argsort(a1, axis=1)
print("정렬 전 인덱스 arr_idx : \n", arr_idx)

# 다차원 인덱스를 적용해 원래 배열을 정렬 시 : np.take_along_axis() 함수
sorted_a1 = np.take_along_axis(a1, arr_idx, axis=1)
print("정렬 후 : \n", sorted_a1)

정렬 전 인덱스 arr_idx : 
 [[1 0 2]
 [0 2 1]
 [2 1 0]]
정렬 후 : 
 [[1 3 6]
 [0 4 7]
 [2 3 5]]


## [array 필터링] <hr>
- BlooeanIndexing => 조건에 맞는 데이터/원소 추출
- 함수 : np.where(array[조건식]) => 조건에 맞는 데이터/원소의 인덱스 튜플로 반환

In [7]:
import numpy as np

In [8]:
arr1d = np.arange(1, 31)

In [9]:
# 필터링 - (1) Boolen Indexing
bool_idx = arr1d % 2 == 0
arr1d[bool_idx]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
# 필터링 - (2) np.where() : 필터링 된 인덱스
idx = np.where(~arr1d % 2)
arr1d[idx]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
# 필터링 - (3) np.all() : 필터링 된 인덱스
arr2d = arr1d.reshape(-1, 10)
print(arr2d)

print(f'axis = None : {np.all(arr2d % 2)} / {np.any(arr2d % 2)}')

print(f'axis = 1 : {np.all(arr2d % 2, axis=1)} / {np.any(arr2d % 2, axis=1)}')

print(f'axis = 0 : {np.all(arr2d % 2, axis=0)} / {np.any(arr2d % 2, axis=0)}')

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
axis = None : False / True
axis = 1 : [False False False] / [ True  True  True]
axis = 0 : [ True False  True False  True False  True False  True False] / [ True False  True False  True False  True False  True False]
