#### [ 데이터 전처리 - 결측치 처리 모듈 sklearn.imputer ]<hr>
- panda에서 결측치 처리 가능
- sklearn에서 결측치 처리 위해 제공
- 방식
    * SimpleImputer : 일반 평균, 중앙값, 최빈값, 사용자지정값 설정해서 채우기
    * KNNImputer : KNN 알고리즘 기반, 결측치와 가장 가까이 있는 K개의 값을 가중평균으로 채우기
    * IterativeImputer : 컬럼의 관련성을 고려해 결측치 채우기 => 실험단계

In [4]:
## -------------------------------------------------------------------
## 모듈 로딩
## -------------------------------------------------------------------
## 데이터 관련 모듈
import pandas as pd 
import numpy as np

## ML 전처리 모듈 - 정제
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import SimpleImputer, KNNImputer, IterativeImputer 


- **SimpleImputer**

In [10]:
## 실습데이터
X = [ [10, 100], [20, np.nan], [30, 300] ]

## 결측치 처리 인스턴스 생성
simImputer = SimpleImputer()
#print(f'fit() 이전 : {simImputer.statistics_}') : XXX_ fit()진행 후 설정 및 생성 => 모델 파라미터

## 결측치 처리 연산 준비
simImputer.fit(X)
print(f'fit() 이후 : {simImputer.indicator_}, {simImputer.statistics_}')

## 결측치 채우기
simImputer.transform(X)

fit() 이후 : None, [ 20. 200.]


array([[ 10., 100.],
       [ 20., 200.],
       [ 30., 300.]])

- **KNNImputer**

In [12]:
## 실습데이터
X = [ [80, 90], [85, np.nan], [20, 30], [25, 35] ]

## 인스턴스 생성
kImputer = KNNImputer(n_neighbors=2)

## 데이터기반 연산 준비
kImputer.fit(X)

## 결측치 채우기
kImputer.transform(X)


array([[80. , 90. ],
       [85. , 62.5],
       [20. , 30. ],
       [25. , 35. ]])

- **IterativeImputer**

In [ ]:
## 실습데이터
## - 키, 몸무게
X = [[170, 70], [180, np.nan], [160, 55], [175, 75]]


## 인스턴스 생성
iterImputer = IterativeImputer()

## 데이터기반 연산 준비
iterImputer.fit(X)

## 결측치 채우기
iterImputer.transform(X)

array([[170.        ,  70.        ],
       [180.        ,  82.43421043],
       [160.        ,  55.        ],
       [175.        ,  75.        ]])