### [ ndarray 병합 및 연결 ] <hr>
- 행 추가 : np.vstack()
- 열 추가 : np.hstack()
- 깊이 추가 : np.dstack() - 3차원 형태로 동작. 내부적으로 3D 변환 후 진행

In [2]:
import numpy as np

In [ ]:
a1 = np.array([[11,22],[33,44]])
a2 = np.array([[55,66],[77,88]])
a3 = np.array([[99,100]])

In [22]:
# 수직 병합 / 수평 병합
# => np.vstack() : 컬럼(열) 수가 일치 해야함
av12 = np.vstack((a1,a2)) # ((2,2), (2,2))
av13 = np.vstack((a1,a3)) # ((2,2), (1,2))

# => np.hstack() : 행 수가 일치 해야함
ah12 = np.hstack((a1,a2)) # ((2,2), (2,2))
ah13 = np.hstack((a1,a3.T)) # ((2,2), (2,1))

print(av12, av13, ah12, ah13, sep='\n\n')

[[11 22]
 [33 44]
 [55 66]
 [77 88]]

[[ 11  22]
 [ 33  44]
 [ 99 100]]

[[11 22 55 66]
 [33 44 77 88]]

[[ 11  22  99]
 [ 33  44 100]]


In [24]:
# 깊이 층 쌓기 : np.dstack()
# => 3D으로 결과 반환
# => 3D 아닌 array는 내부에서 변환 후 처리
a1 = np.array([11,22,33])
a2 = np.array([44,55,66])

ad12 = np.dstack((a1,a2))

print(ad12.shape, ad12, sep='\n\n')

(1, 3, 2)

[[[11 44]
  [22 55]
  [33 66]]]


In [25]:
# => 3D으로 결과 반환
# => 3D 아닌 array는 내부에서 변환 후 처리
a1 = np.array([[11,22],[33,44]])
a2 = np.array([[55,66],[77,88]])

ad12 = np.dstack((a1,a2))

print(ad12.shape, ad12, sep='\n\n')

(2, 2, 2)

[[[11 55]
  [22 66]]

 [[33 77]
  [44 88]]]
