### [ ndarray 분활 ] <hr>
- np.hsplit() : 수평/컬럼을 분할하는 함수
- np.vsplit() : 수직/컬럼을 분할하는 함수
- np.split() : aixs 매개변수 설정에 따른 분할하는 함수

In [1]:
import numpy as np

In [3]:
arr = np.arange(1,13).reshape((3,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# 수평분할
a1, a2 = np.hsplit(arr, 2)
print(a1, a2, sep='\n\n')

# => np.hsplit(array, (분활인덱스))
a1, a2, a3 = np.hsplit(arr, (1,3)) # 0 ~ (1-1), 1 ~ (3-1), 3 ~
print(a1, a2, a3, sep='\n\n')

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 3  4]
 [ 7  8]
 [11 12]]
[[1]
 [5]
 [9]]

[[ 2  3]
 [ 6  7]
 [10 11]]

[[ 4]
 [ 8]
 [12]]


In [11]:
# 수직분활
arr = np.arange(18).reshape((6,3))
a1, a2 = np.vsplit(arr, 2)
print(a1, a2, sep='\n\n')

# => np.hsplit(array, (분활인덱스))
a1, a2, a3 = np.vsplit(arr, (1,3)) # 0 ~ (1-1), 1 ~ (3-1), 3 ~
print(a1, a2, a3, sep='\n\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[0 1 2]]

[[3 4 5]
 [6 7 8]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
