### [ 유니버설 함수 - Numpy 성능 핵심요소 ] <hr>
- 반복문 없이 원소 단위 연산 수행
- 자동 타입과 형태 변화 최적화 진행 => 브로드캐스팅 자동 진행

In [ ]:
import numpy as np

In [9]:
arr = np.array([3.2, 0.1, 8., -5.2, -3.12, -1.7])

In [10]:
# 실수 데이터 => 소수점 이하 자릿수 관련 함수
# => np.ceil() 소수점 이하 올림 처리
print(f'원본 : {arr}')
print(f'자릿수 처리 (올림) : {np.ceil(arr)}')

원본 : [ 3.2   0.1   8.   -5.2  -3.12 -1.7 ]
자릿수 처리 (올림) : [ 4.  1.  8. -5. -3. -1.]


In [12]:
# => np.round() 소수점 이하 반올림 처리
print(f'원본 : {arr}')
print(f'자릿수 처리 (반올림) : {np.round(arr)}')

원본 : [ 3.2   0.1   8.   -5.2  -3.12 -1.7 ]
자릿수 처리 (반올림) : [ 3.  0.  8. -5. -3. -2.]


In [14]:
# => np.floor() 소수점 이하 내림 처리
print(f'원본 : {arr}')
print(f'자릿수 처리 (내림) : {np.floor(arr)}')

원본 : [ 3.2   0.1   8.   -5.2  -3.12 -1.7 ]
자릿수 처리 (내림) : [ 3.  0.  8. -6. -4. -2.]


In [ ]:
# 누적 연산 처리 함수
arr = np.arange(1, 10, 3)

# => 연산.reduce(array_obj) : 누적 연산 결과 반환
result1 = np.add.reduce(arr)

result2 = np.multiply.reduce(arr)

print(f'{arr} => {result1}')
print(f'{arr} => {result2}')

[1 4 7] => 12
[1 4 7] => 28


In [27]:
# 누적 연산 처리 함수
arr = np.arange(1, 17).reshape(4,4)

# => 2개 컬럼만 묶어서 연산
retarr = np.add.reduceat(arr, [0,2])

print(f'{arr} \n --연산후-- \n {retarr}')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
 --연산후-- 
 [[ 6  8 10 12]
 [22 24 26 28]]
