In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# 행렬의 기본 연산
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
print(A+B) 
print(A*B)

[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]


#### 행렬 곱셈 규칙
- 첫 번째 행렬의 열의 수(n)와 두 번째 행렬의 행의 수(n)가 같아야 됨
    - A(m x n) x B(n x p) = C(m x p)

- Numpy 행렬 곱셈
    - np.dot(A, B): 내적 및 행렬곱
    - np.matmul(A, B): 행렬의 곱셈 연산 전용(다차원 지원)
    - A @ B: 행렬곱 연산자 (Python 3.5 이후)


- 내적(Dot Product, Inner Product)
    - 1차원 벡터 : 같은 위치에 있는 원소끼리 곱한 후 모두 더한 값
    - 2차원 배열(행렬) : 행렬 곱셈

In [6]:
# 1차원 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

np.int64(32)

In [9]:
# 2차원 행렬의 곱(dot()과 matmul() 연산 결과 동일)
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(f'np.dot(A,B) : \n{np.dot(A, B)}')
print(f'A @ B : \n{A @ B}')
print(f'np.matmul(A,B) : \n{np.matmul(A,B)}')

np.dot(A,B) : 
[[19 22]
 [43 50]]
A @ B : 
[[19 22]
 [43 50]]
np.matmul(A,B) : 
[[19 22]
 [43 50]]


In [12]:
# 3차원 배열 dot(A, B) 연산
A = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
B = np.array([[[9, 10],[11, 12]],[[13, 14],[15, 16]]])
print(f'np.dot(A, B) : \n{np.dot(A, B)}')

np.dot(A, B) : 
[[[[ 31  34]
   [ 43  46]]

  [[ 71  78]
   [ 99 106]]]


 [[[111 122]
   [155 166]]

  [[151 166]
   [211 226]]]]


In [41]:
# 3차원 배열 matmul(a, b) 또는 @ 연산
A = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
B = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print(f'np.matmul(A,B) \n{np.matmul(A,B)}')
print('-' * 10)
print(f'A @ B \n{A @ B}')

np.matmul(A,B) 
[[[ 31  34]
  [ 71  78]]

 [[155 166]
  [211 226]]]
----------
A @ B 
[[[ 31  34]
  [ 71  78]]

 [[155 166]
  [211 226]]]


In [ ]:
# 두 벡터(1차원)를 이용하여 새로운 행렬을 만드는 연산: 모든 가능한 곱셈 조합을 계산
# np.outer(a, b): 두 벡터의 외적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 외적 계산
outer_product = np.outer(a, b)
print(f"외적 결과: \n{outer_product}")


외적 결과: 
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
# 전치 행렬 : 행과 열을 서로 바꾼 행렬
# A = (m x n)행렬, 전치행렬(AT) = (n x m)
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A) # A.shape : (2, 3)
print('-' * 20)
# 방법 1: .T 속성
print('전치행렬 A.T')
trans_a = A.T
print(trans_a)
print(f'A.T.shape: {trans_a.shape}')
print('-' * 20)
# 방법 2: transpose() 함수
print('np.transpose(A)')
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
--------------------
전치행렬 A.T
[[1 4]
 [2 5]
 [3 6]]
A.T.shape: (3, 2)
--------------------
np.transpose(A)
[[1 4]
 [2 5]
 [3 6]]


In [46]:
# 역행렬 함수
# np.linalg.inv(arr): 행렬 arr의 역행렬 계산
# np.linalg.det(arr): 행렬 arr의 역행렬이 존재하는지 검사
matrix = np.array([[1, 2], [3, 4]])

# 역행렬 계산
inv_matrix = np.linalg.inv(matrix)
print(f"원본 행렬: \n{matrix} \n\n 역행렬 : \n{inv_matrix}")

# 역행렬이 존재하는지 확인 (행렬식이 0이 아님)
det_matrix = np.linalg.det(matrix)
print(f"\n행렬식: {det_matrix}")
if det_matrix != 0: print("역행렬이 존재합니다!")
else: print("역행렬이 존재하지 않습니다.")

원본 행렬: 
[[1 2]
 [3 4]] 

 역행렬 : 
[[-2.   1. ]
 [ 1.5 -0.5]]

행렬식: -2.0000000000000004
역행렬이 존재합니다!


In [ ]:
# 1차원 배열 정렬
# np.sort(array이름): 원본(array)은 변경 없고, 정렬된 배열을 반환 (기본 오름차순 정렬)
# array이름.sort()  : 원본이 변경되며, 반환값은 None
arr = np.array([4, 2, 6, 5, 1, 3, 0])

# 정렬 (원본 유지)
sorted_arr = np.sort(arr)
print(f'정렬된 배열: {sorted_arr}') # [0 1 2 3 4 5 6]

# 원본 변경
arr.sort()
print(f'원본변경: {arr}') # [0 1 2 3 4 5 6]

# 내림차순
desc_arr = np.sort(arr)[::-1]
print(f'내림차순: {desc_arr}') # [6 5 4 3 2 1 0]
print(f'원본배열: {arr}')

정렬된 배열: [0 1 2 3 4 5 6]
원본변경: [0 1 2 3 4 5 6]
내림차순: [6 5 4 3 2 1 0]
원본배열: [0 1 2 3 4 5 6]


In [49]:
# 2차원 배열 정렬
# np.sort(array, axis=1): 행(row) 정렬
# np.sort(array, axis=0): 열(column) 정렬

# 2차원 배열 정렬
arr2d = np.array([[3, 1, 6], [0, 7, 4], [5, 3, 2]])

# 행별 정렬 (axis=1)
print('sort(axis=1)')
row_sorted = np.sort(arr2d, axis=1)
print(row_sorted, "\n")

# 열별 정렬 (axis=0)
print('sort(axis=0)')
col_sorted = np.sort(arr2d, axis=0)
print(col_sorted, "\n")

# axis=None (1차원 배열로 변경 후 정렬 )
print('sort(axis=None)')
none_sort = np.sort(arr2d, axis=None)
print(none_sort, "\n")

sort(axis=1)
[[1 3 6]
 [0 4 7]
 [2 3 5]] 

sort(axis=0)
[[0 1 2]
 [3 3 4]
 [5 7 6]] 

sort(axis=None)
[0 1 2 3 3 4 5 6 7] 



In [51]:
# argsort(array)
# 배열(array)의 요소를 정렬했을 때의 정렬 전 배열의 인덱스를 반환
# 배열을 정렬할 때 각 원소가 어디에 위치해야 되는지 알려줌 => 직접 배열을 정렬하지는 않음
arr = np.array([4, 2, 3, 5, 1])
print(f'원본 배열: {arr}')

# 배열을 정렬할 때, 각 원소가 어디에 위치해야 되는지 알려줌
indices = np.argsort(arr)
print(f'정렬시 원소 인덱스: {indices}')

# indices로 배열 정렬 가능
print(f'배열 정렬: {arr[indices]}')

# 배열 정렬: np.sort()
print(f'배열 정렬: {np.sort(arr)}')

원본 배열: [4 2 3 5 1]
정렬시 원소 인덱스: [4 1 2 0 3]
배열 정렬: [1 2 3 4 5]
배열 정렬: [1 2 3 4 5]


In [ ]:
fruit_array = np.array(['Apple', 'Banana', 'Cherry', 'Grape', 'Kiwi'])
price_array = np.array([800, 1000, 900, 950, 700]) 
desc_price  = np.sort(price_array)[::-1]
print(f'price 내림차순 정렬: {desc_price}')

# 정렬 인덱스 저장: [::-1]를 붙일 경우 내림차순
score_indices = np.argsort(price_array)[::-1] # score_indices: [1 3 2 0 4]
print(fruit_array[score_indices]) # 정렬된 가격 순서대로 fruit을 출력

price 내림차순 정렬:	[1000  950  900  800  700]
['Banana' 'Grape' 'Cherry' 'Apple' 'Kiwi']


In [ ]:
# 기본 병합
# 수직 병합(행 추가): np.vstack([array1, array2])
# 수평 병합(열 추가): np.hstack([array1, array2])

a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

# 수직 병합 (행 추가)
vstack_result = np.vstack([a, b])
print(vstack_result)
print('-' * 20)

# 수평 병합 (열 추가)
hstack_result = np.hstack([a, b])
print(hstack_result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# np.dstack(tuple): depth stack
# 깊이 방향(axis=2)으로 배열을 쌓아 올림
# 병합할 축을 제외한 shape가 모두 동일해야 됨
# 튜플 형태로 배열 전달: (a, b)
# 1차원 배열 dstack((a, b))
# 내부적으로 3차원으로 reshape()후 병합
# 1차원 배열(N, ) -> 3차원 (1, N, 1) 형태로 변환
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.dstack((arr1, arr2))

print(result)
print(result.shape) # (1, 3, 2)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [ ]:
# 2차원 배열 dstack()
# 내부적으로 3차원으로 reshape() 후 병합
# 2차원 배열(M, N) -> 3차원 (M, N, 1) 형태로 변환
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.dstack((arr1, arr2))

print(result)
print(result.shape) # (2, 2, 2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [ ]:
# 3차원 배열 dstack()
# 차원을 추가하지 않고 단순히 병합

# 2개의 3차원 배열(2x2x3) 생성
arr1 = np.array([[[1, 2, 3], 
                  [4, 5, 6]],
                 [[7, 8, 9], 
                  [10, 11, 12]]])
arr2 = np.array([[[13, 14, 15], 
                  [16, 17, 18]],
                 [[19, 20, 21], 
                  [22, 23, 24]]])
print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)

result = np.dstack((arr1, arr2))
print("result shape:", result.shape)
print(result)

arr1	shape: (2, 2, 3)
arr2	shape: (2, 2, 3)
result	shape: (2, 2, 6)
[[[ 1  2  3 13 14 15]
  [ 4  5  6 16 17 18]]

 [[ 7  8  9 19 20 21]
  [10 11 12 22 23 24]]]


In [ ]:
# concatenate((arr1, arr2, …), axis=0)
# axis의 값에 따라 병합할 배열의 차원이 일치해야 됨
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])
# axis=0 (수직)
concat_0 = np.concatenate([a, b], axis=0)
print(concat_0)
print()

# axis=1 (수평)
concat_1 = np.concatenate([a, b], axis=1)
print(concat_1)
print()

# axis=None (1차원 배열로 평탄화)
concat_none = np.concatenate([a, b], axis=None)
print(concat_none)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]

[1 2 3 4 5 6 7 8]


In [ ]:
# hsplit(): column-wise 분할
# np.hsplit(arr, n) 또는 np.split(arr, n, axis=1)
# 컬럼(axis=1)을 기준으로 n개의 동일한 크기로 분할 (수직 방향으로 분할)
arr = np.arange(12).reshape(3, 4)
print(arr)

# 수평 분할 (컬럼 기준)
h_splits = np.hsplit(arr, 2) # 수직 2등분

# h_splits = np.split(arr, 2, axis=1)
print(h_splits[0])
print(h_splits[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# vsplit(): row-wise 분할
# np.vsplit(arr, n) 또는 np.split(arr, n, axis=0)
# 행(axis=0)을 기준으로 n개의 동일한 크기로 분할 (수평 방향으로 분할)
# 수직 축 기준: 분할된 배열이 모든 컬럼을 포함
arr = np.arange(12).reshape(3, 4)
print(arr)

# 수직 분할 (행 기준)
v_splits = np.vsplit(arr, 3)

# v_splits = np.split(arr, 3, axis=0)
print(v_splits)
print(f'v_splits[0]: {v_splits[0]}')
print(f'v_splits[1]: {v_splits[1]}')
print(f'v_splits[2]: {v_splits[2]}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
v_splits[0]:	[[0 1 2 3]]
v_splits[1]:	[[4 5 6 7]]
v_splits[2]:	[[ 8  9 10 11]]


In [ ]:
# hsplit(array, [index1, index2]) 또는 hsplit(array, (index1, index2))
# index1과 index2에서 분할
# (0 ~ index1-1), (index1 ~ index2-1), (index2 ~ 끝까지)
arr1 = np.arange(12).reshape(3, 4)

# h_splits = np.hsplit(arr1, (1, 3))
h_splits = np.hsplit(arr1, [1, 3])
print(h_splits[0])
print(h_splits[1])
print(h_splits[2])
print('-' * 20)

arr2 = np.arange(18).reshape(3, 6)
print(arr2)

h_splits = np.hsplit(arr2, (2, 4))
print(h_splits[0])
print(h_splits[1])
print(h_splits[2])

[[0]
 [4]
 [8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3]
 [ 7]
 [11]]
--------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 0  1]
 [ 6  7]
 [12 13]]
[[ 2  3]
 [ 8  9]
 [14 15]]
[[ 4  5]
 [10 11]
 [16 17]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# view(): 얕은 복사 (메모리 공유)
view_arr = arr.view()
view_arr[0] = 100 # view_arr 수정
print(f'원본 배열(arr): {arr}') # 원본 변경
print(f'view 배열(view_arr): {view_arr}')

# copy(): 깊은 복사 (독립적인 메모리)
arr = np.array([1, 2, 3, 4, 5])
copy_arr = arr.copy()
copy_arr[0] = 100 # copy_arr 수정
print(f'원본 배열(arr): {arr}') # 원본 변경 안됨
print(f'copy 배열(copy_arr): {copy_arr}') # copy_arr만 변경

원본 배열(arr):	[100   2   3   4   5]
view 배열(view_arr):	[100   2   3   4   5]
원본 배열(arr):	[1 2 3 4 5]
copy 배열(copy_arr):	[100   2   3   4   5]


- 유니버설 함수(ufunc)
    - 배열의 각 원소에 대해 반복문 없이 한 번에 연산을 적용하는 Numpy의 함수
    - 하나의 함수를 사용해서 모든 원소에 자동으로 적용
    - ufunc를 호출하면 입력된 모든 배열에 자동으로 브로드캐스팅이 적용

- 파이썬의 for 문장
    - 각 원소마다 데이터 타입을 확인하고 함수 호출을 반복
    - 대용량 데이터 연산에서 느림

- 유니버설 함수의 특징
    - Element-wise 연산: 원소별 연산
    - 배열의 같은 인덱스에 위치한 요소들끼리 연산을 수행

- 벡터화 연산
    - 벡터화 의미: 반복문 없이 배열 전체에 수학적 연산을 한 번에 수행
    - 배열의 각 요소에 대해 같은 연산을 수행하는 것을 의미

- 입력 데이터의 타입과 크기에 따라 자동으로 최적화
    - 브로드캐스팅과 함께 사용

In [ ]:
# 단항 유니버설 함수: 1개의 배열에 적용하는 함수
# np.abs(), np.sqrt(), np.exp(), np.sin(), np.log(), np.rint()

arr = np.array([-2.5, -1.2, 0, 1.7, 3.4])
print(f'np.ceil(): {np.ceil(arr)}') # 올림
print(f'np.floor(): {np.floor(arr)}') # 내림
print(f'np.rint(): {np.rint(arr)}') # 가장 가까운 정수로 반올림(부동소수점 형태) 
print(f'np.round(): {np.round(arr, 0)}') # 지정된 자리수로 반올림 (정수 또는 부동소수점)
print(f'np.abs(): {np.abs(arr)}') # 절대값
print(f'np.sqrt(): {np.sqrt(np.abs(arr))}') # 제곱근

# 삼각함수
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print(np.sin(angles))
print(np.cos(angles))

np.ceil():	[-2. -1.  0.  2.  4.]
np.floor():	[-3. -2.  0.  1.  3.]
np.rint():	[-2. -1.  0.  2.  3.]
np.round():	[-2. -1.  0.  2.  3.]
np.abs():	[2.5 1.2 0.  1.7 3.4]
np.sqrt():	[1.58113883 1.09544512 0.         1.30384048 1.84390889]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]


In [ ]:
# 연산.reduce(array)
# 결과가 하나만 남을 때까지 해당 연산(add)을 배열 원소에 반복 적용
# 연산.accumulate(array)
# 연산 결과를 누적해서 저장
x = np.arange(1, 6) # [1, 2, 3, 4, 5]

# reduce(x) 
y = np.add.reduce(x)
print(y)
y = np.multiply.reduce(x)
print(y)

# accumulate(x)계산 중 결과를 누적해서 저장
print(x)
y = np.add.accumulate(x)
print(y)

15
120
[1 2 3 4 5]
[ 1  3  6 10 15]


In [ ]:
# reduceat(array, indices, axis=0)
# 주어진 배열에서 indices로 시작 위치를 지정(구간 설정)
# 구간별 누적 연산 수행
# axis와 index를 지정
# 구간별 부분 집계(add, multiply 등) 적용

arr = np.array([1, 2, 3, 4, 5, 6])
indices = [0, 3] # [0,3): 1+2+3, [3:]: 4+5+6
result = np.add.reduceat(arr, indices)
print(result) # [6 15]
result = np.multiply.reduceat(arr, [0, 2, 4])
print(result)

[ 6 15]
[ 2 12 30]


In [36]:
# 2차원 배열에서 구간별 합 구하기
arr = np.arange(1, 13).reshape(4, 3)
print("원본 배열:")
print(arr)
# 0~2행, 2~4행을 아래로 합침 (indices=[0,2])
result = np.add.reduceat(arr, [0, 2], axis=0)
print(result)
arr = np.arange(1, 13).reshape(4, 3)
print("원본 배열:")
print(arr)
# 각 행 별로 첫 번째와 두 번째 열, 나머지 열을 합산
result = np.add.reduceat(arr, [0, 2], axis=1)
print(result)

원본 배열:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  7  9]
 [17 19 21]]
원본 배열:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  3]
 [ 9  6]
 [15  9]
 [21 12]]


In [37]:
arr = np.arange(10).reshape(2,5)
print(arr)
# indices=[0,2,4] → [0:2], [2:4], [4:]
result = np.multiply.reduceat(arr, [0,2,4], axis=1)
print(result)
print('-' * 20)
arr = np.arange(1, 17).reshape(4,4)
print(arr)
# 열 방향으로 구간합, 그 후 행 방향으로 또 reduceat 적용
result = np.add.reduceat(arr, [0,2], axis=1)
print(result)
final = np.add.reduceat(result, [0,2], axis=0)
print(final)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  6  4]
 [30 56  9]]
--------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 3  7]
 [11 15]
 [19 23]
 [27 31]]
[[14 22]
 [46 54]]


In [ ]:
# 이항 유니버설 함수: 두 개의 배열에 적용하는 연산
x = np.array([1, 9, 3, 4])
y = np.array([5, 6, 7, 8])
print(f'add(): {np.add(x, y)}') # 덧셈
# 인덱스별로 비교해서 큰 값/작은 값 반환
print(f'np.maximum(x, y): {np.maximum(x, y)}') 
print(f'np.minimum(x, y): {np.minimum(x, y)}') 
# 거듭제곱
print(f'np.power(x, 2): {np.power(x, 2)}')
# modf: 정수부와 소수부 분리
arr = np.array([3.14, -2.7, 5.8])
fractional, integer = np.modf(arr)
print(f"정수부: {integer}")
print(f"소수부: {fractional}")

In [9]:
# 논리 연산 및 브로드캐스팅
# 브로드캐스팅 활용
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([10, 20, 30])
print(np.add(x, y))
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])

# 논리 연산
print(f'np.greater(a, b): {np.greater(a, b)}')

# a>1 and b<3 
print(f'np.logical_ad(a>1, b<3): {np.logical_and(a>1, b<3)}')

[[11 22 33]
 [14 25 36]]
np.greater(a, b): [False False  True]
np.logical_ad(a>1, b<3): [False  True  True]


In [12]:

import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])
print(np.add(x, y))

a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
print(np.greater(a, b))
print(np.logical_and(a > 1, b < 3))

[[11 22 33]
 [14 25 36]]
[False False  True]
[False  True  True]
