In [2]:
# -----------------------------------------
# 개발환경 설치된 패키지 체크
# -----------------------------------------
# 모듈 로딩
import pandas as pd 
import matplotlib as mp
import sklearn as sk
import cv2
import numpy as np
import torch

# 버전 정보 출력
print(f'pandas     v.{pd.__version__}')
print(f'matplotlib v.{mp.__version__}')
print(f'sklenrn    v.{sk.__version__}')
print(f'opencv     v.{cv2.__version__}')
print(f'numpy      v.{np.__version__}')
print(f'pytorch    v.{torch.__version__}')
print(f'pytorch    v.{torch.cuda.is_available()}')
print(torch.cuda.get_device_name())
print(torch.cuda.get_device_capability())

pandas     v.3.0.3
matplotlib v.3.11.0
sklenrn    v.1.9.0
opencv     v.4.13.0
numpy      v.2.4.6
pytorch    v.2.11.0+cu128
pytorch    v.True
NVIDIA GeForce RTX 5060 Laptop GPU
(12, 0)


In [3]:
# 생성 및 타입
tensor1d = torch.tensor([1,2,3])
print(tensor1d)

tensor2d = torch.tensor([[1,2,3],[4,5,6]])
print(tensor2d)

et = torch.eye(3,5)
print(et)

rand_tensor = torch.rand((3,3))
print(rand_tensor)

t = torch.linspace(0,2,4)
print(t)

float_t = torch.tensor([1,2,3], dtype=torch.float32)
print(float_t.dtype)

int_t = torch.tensor([1,2,3], dtype=torch.int64)
print(int_t.dtype)

double_t = int_t.double()
print(double_t.dtype)

float_t = int_t.float()
print(float_t.dtype)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
tensor([[0.7418, 0.1203, 0.5116],
        [0.1241, 0.2335, 0.3427],
        [0.7231, 0.7867, 0.3763]])
tensor([0.0000, 0.6667, 1.3333, 2.0000])
torch.float32
torch.int64
torch.float64
torch.float32


In [37]:
torch.eye(3,5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [5]:
# 연산
a = torch.tensor([1,2,3])
b = torch.tensor([10])
print(a+b)

tensor([11, 12, 13])


In [6]:
# 불리언 마스킹
t = torch.tensor([[10,20,30],
                  [40,50,60],
                  [70,80,90]])

# t 복사
t2 = t.clone()
print(t2)
mask = t2 > 50
print(mask)
print(t2[mask])
t2[mask] = 1
print(t2)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])
tensor([[10, 20, 30],
        [40, 50,  1],
        [ 1,  1,  1]])


In [7]:
# 복합 마스킹
mask = (t > 30) & (t < 80)
print(t[mask])

tensor([40, 50, 60, 70])


In [8]:
# reshape 쓰자
t_flat = torch.arange(6)
t_flat.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [9]:
# 합치기
t1 = torch.arange(1,4)
t2 = torch.arange(4,7)
t3 = torch.cat((t1, t2))
print(t3.shape)
print(t3)

# 쌓기
t4 = torch.stack((t1, t2))
print(t4.shape)
print(t4)

torch.Size([6])
tensor([1, 2, 3, 4, 5, 6])
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
# 특정 크기씩 잘라 반환
split = torch.split(t3, 3)
print(split)

# 편함
split = t3.split(3)
print(split)


# 개수 기준 나눔
chunk = torch.chunk(t3, 3)
print(chunk)

chunk = t3.chunk(3)
print(chunk)

(tensor([1, 2, 3]), tensor([4, 5, 6]))
(tensor([1, 2, 3]), tensor([4, 5, 6]))
(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))
(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [11]:
# 2차원 행/열 뒤집기
print(t4)
transpose = t4.t()
transpose

tensor([[1, 2, 3],
        [4, 5, 6]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [12]:
# 3차원 이상 차원 순서 바꾸기
t_3d = torch.rand(2,3,4)
print(t_3d)
t_3d.permute(2,1,0)

tensor([[[0.4348, 0.8798, 0.6457, 0.5204],
         [0.7128, 0.8751, 0.4918, 0.5909],
         [0.7583, 0.5912, 0.4946, 0.2624]],

        [[0.6941, 0.5153, 0.0850, 0.8537],
         [0.9650, 0.8547, 0.4492, 0.5551],
         [0.1042, 0.3737, 0.0886, 0.2408]]])


tensor([[[0.4348, 0.6941],
         [0.7128, 0.9650],
         [0.7583, 0.1042]],

        [[0.8798, 0.5153],
         [0.8751, 0.8547],
         [0.5912, 0.3737]],

        [[0.6457, 0.0850],
         [0.4918, 0.4492],
         [0.4946, 0.0886]],

        [[0.5204, 0.8537],
         [0.5909, 0.5551],
         [0.2624, 0.2408]]])

In [13]:
# 차원이 1인 축을 제거 / 추가
t = torch.tensor([[[1,2,3]]])
print(t.shape)
print(t.squeeze().shape)
print(t.squeeze().unsqueeze(0).shape)

torch.Size([1, 1, 3])
torch.Size([3])
torch.Size([1, 3])


In [14]:
print(t)
t.contiguous() # ?

tensor([[[1, 2, 3]]])


tensor([[[1, 2, 3]]])

In [15]:
# as_tensor() = 뭐든 받아서 => tensor 
num = list(range(1,100))
torch.as_tensor(num)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
import numpy as np
np = np.array([1,2,3])
t = torch.as_tensor(np)
t

tensor([1, 2, 3])

In [17]:
# 변환시 메모리 공유 -> 안되면 말고
np[0] = 100
t[2] = 300
print(np)
print(t)

[100   2 300]
tensor([100,   2, 300])


In [18]:
# numpy -> tensor
import numpy as np
np = np.array([1,2,3])
t = torch.from_numpy(np)
t

tensor([1, 2, 3])

In [19]:
# tensor -> numpy
np = t.numpy()
np

array([1, 2, 3])

In [20]:
# from_numpy 변환시 항상 메모리 공유 -> 안되면 에러
np[0] = 100
t[2] = 300
print(np)
print(t)
# as_tensor() 쓰자

[100   2 300]
tensor([100,   2, 300])


In [21]:
import numpy as np
np = np.array([1,2,3])
t = torch.tensor(np) # ndarray 데이터 복사(copy)하여서 텐서 객체 생성
t

tensor([1, 2, 3])

In [22]:
np[0] = 100
t[2] = 300
print(np)
print(t)

[100   2   3]
tensor([  1,   2, 300])


In [23]:
# numpy는 GPU 접근 불가
# GPU tensor는 .cpu()를 통해 CPU로 이동해야 호환가능
if torch.cuda.is_available():
    gpu_t = torch.tensor([1,2,3], device='cuda')
    try : 
        gpu_np = gpu_t.cpu().numpy()
        print(gpu_np)
    # try : 
    #     gpu_np = gpu_t.numpy()
    #     print(gpu_np)
    except TypeError: 
        print(TypeError)
    print(gpu_t)

[1 2 3]
tensor([1, 2, 3], device='cuda:0')


In [24]:
print(gpu_t.device)
print(gpu_np.device)

cuda:0
cpu


In [25]:
# cpu vs gpu
import time
size = 10000

a_cpu = torch.rand((size, size))
b_cpu = torch.rand((size, size))

start_time = time.time()
# 연산 결과는 필요없으니 버림
_ = torch.mm(a_cpu, b_cpu)
# 연산 시간
cpu_time = time.time() - start_time
print(f'cpu_time : {cpu_time}')

if torch.cuda.is_available():
    a_gpu = a_cpu.to('cuda')
    b_gpu = b_cpu.to('cuda')

    torch.cuda.synchronize()
    start_time = time.time()
    _ = torch.mm(a_gpu, b_gpu)
    gpu_time = time.time() - start_time
    print(f'gpu_time : {gpu_time}')


cpu_time : 3.317614793777466
gpu_time : 0.20331621170043945


In [26]:
# 종합 실습
a = torch.arange(1,6)
b = torch.arange(6,11)

print(f'a+b : {a+b}')
print(f'a*b : {a*b}')

c = torch.tensor([[1],[2],[3]])
d = torch.tensor([10,20,30])
print(f'브로드캐스팅 c+d:\n {c+d}')

np_a = a.numpy()
np_b = b.numpy()
print(f'a + b : {a + b}')
print(f'np_a + np_b : {np_a + np_b}')

a+b : tensor([ 7,  9, 11, 13, 15])
a*b : tensor([ 6, 14, 24, 36, 50])
브로드캐스팅 c+d:
 tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
a + b : tensor([ 7,  9, 11, 13, 15])
np_a + np_b : [ 7  9 11 13 15]


In [27]:
# 연습문제 1
x = torch.linspace(0,1,10)
x + 5

tensor([5.0000, 5.1111, 5.2222, 5.3333, 5.4444, 5.5556, 5.6667, 5.7778, 5.8889,
        6.0000])

In [28]:
# 연습문제 2
t = torch.arange(1,17).reshape(4,4)
print(t)
print(t[2][3])
print(t[-2:])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor(12)
tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [29]:
# 연습문제 3
t = torch.randn(5,5)
mask = t < 0
t[mask]

tensor([-0.5381, -1.5976, -0.5619, -0.3786, -1.1076, -0.9454, -0.9645, -1.2057,
        -0.3183, -1.5096, -0.3478, -2.4018, -0.3384, -0.2290, -1.0719, -0.1668,
        -0.2228])

In [30]:
# 연습문제 4
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])

stack = torch.stack((t1, t2))
print(stack)
print(stack.shape)
print(torch.cat((t1,t2)))


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([1, 2, 3, 4, 5, 6])


In [31]:
# 연습문제 5
size = 5000
a_cpu = torch.rand((size, size))
b_cpu = torch.rand((size, size))

start_time = time.time()
_ = torch.mm(a_cpu, b_cpu)
cpu_time = time.time() - start_time
print(f'cpu_time : {cpu_time}')

if torch.cuda.is_available():
    a_gpu = a_cpu.to('cuda')
    b_gpu = b_cpu.to('cuda')

    torch.cuda.synchronize()
    start_time = time.time()
    _ = torch.mm(a_gpu, b_gpu)
    gpu_time = time.time() - start_time
    print(f'gpu_time : {gpu_time}')
    print(cpu_time - gpu_time)

cpu_time : 1.4468626976013184
gpu_time : 0.011547327041625977
1.4353153705596924
