### 선형대수(Linear Algegra)
- 숫자로 구성된 데이터를 다룰때 사용되는 학문
- 데이터를 다루는 방법을 표시한 기호이자 언어
- 연립방정식을 사용하여 미지수의 값을 구하는 데이터분석 도구
- 직선(선형) 세계를 탐구하는 학문
- 데이터를 벡터 공간에 표현하며 선형사상(Linear Mapping) 통해
데이터 변형


* 데이터 종류 - (1) 스칼라 Scalar
    - 1개 숫자
    - 보통 알파벳 소문자로 표기
    - 실수 중 하나의 숫자
    - x∈R 표기 ( R : 실수(real numbers)의 집합 )

* 데이터 종류 - (2) 벡터 Vector
    - 특정한 순서를 가진 여러개 숫자 묶음
    - 가로 방향 묶음 행(row) 벡터, 세로 방향 묶음 열(column) 벡터
    - 행(row)벡터는 데이터 레코드(data record)
    - 하나의 벡터를 이루는 데이터 개수가 n개면 이 벡터를 n-차원 벡터
    - 차원 개념 : 벡터를 구성하는 요소(데이터)의 개수

* 데이터 종류 - (3) 행렬 Matrix
    - 복수의 차원을 가지는 벡터가 여러 개 모인 것
    - 대문자로 표기
    - 행 x 열

* 데이터 종류 - (4) 텐서 Tensor
    - 같은 크기의 행렬(matrix)이 여러 개 같이 묶여 있는 것
    - 물리와 수학에서의 개념으로 벡터 계산을 단순화하여 표기한 것
    - 같은 성질의 여러 벡터를 한 행렬 안에 표기
    - 여러 벡터 공간 및 그 쌍대 공간들을 일종의 '곱연산'을 사용해 복합적으로
연결시킨 구조

#### 데이터 변형 방법 - 전치(Transpose) 연산
- 행렬에서 가장 기본 연산으로 행렬의 행과 열을 바꾸는 연산
- 벡터의 방향을 바꿔서 연산이 가능하게 만드는 역할
- 벡터나 행렬에 T라는 위첨자(superscript)를 붙여서 표기
- 프라임(prime)기호 ′를 붙이는 경우도 있음
- 전치 연산 : x → x ** T / x → x′
<hr>


### [NUMPY BASIC] 
* pandas와 numpy 이해

In [1]:
# 파이썬에 배열(Array) 기능 제공 라이브러리 numpy
import numpy as np
import pandas as pd

In [2]:
# DF 생성
df = pd.DataFrame([[11,22,33], [44,55,66]])

In [3]:
# DF 속성들
print(f'index   => {df.index}')
print(f'columns => {df.columns}')
print(f'values  => {type(df.values)}')
print(df.values)

index   => RangeIndex(start=0, stop=2, step=1)
columns => RangeIndex(start=0, stop=3, step=1)
values  => <class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]]


In [4]:
# SR 속성들
sr = df.iloc[0]
print(f'index   => {sr.index}')
print(f'values  => {type(sr.values)}')
print(sr.values)

index   => RangeIndex(start=0, stop=3, step=1)
values  => <class 'numpy.ndarray'>
[11 22 33]


#### [ Ndarray 객체 생성 방법들 ] <hr>

In [5]:
# [방법1] np.array()
arr1 = np.array([11,22,33])

print(arr1)
print(f'shape    = {arr1.shape}')
print(f'ndim     = {arr1.ndim}')
print(f'dtype    = {arr1.dtype}')
print(f'itemsize = {arr1.itemsize}')
print(f'data     = {arr1.data}')

[11 22 33]
shape    = (3,)
ndim     = 1
dtype    = int64
itemsize = 8
data     = <memory at 0x000001FF006728C0>


In [6]:
arr1 = np.array([[11,22,33],[44,55,66]])

print(arr1)
print(f'shape    = {arr1.shape}')
print(f'ndim     = {arr1.ndim}')
print(f'dtype    = {arr1.dtype}')
print(f'itemsize = {arr1.itemsize}')
print(f'data     = {arr1.data}')
print(f'strides  = {arr1.strides}') # (행이동 메모리칸수, 열이동 메모리 칸수)

[[11 22 33]
 [44 55 66]]
shape    = (2, 3)
ndim     = 2
dtype    = int64
itemsize = 8
data     = <memory at 0x000001FF7E2FAA80>
strides  = (24, 8)


In [7]:
arr1 = np.array([[11,22,33]], dtype=np.int16) # 1개 데이터 저장에 메모리 2칸 사용

print(arr1)
print(f'shape    = {arr1.shape}')
print(f'ndim     = {arr1.ndim}')
print(f'dtype    = {arr1.dtype}')
print(f'itemsize = {arr1.itemsize}')
print(f'data     = {arr1.data}')
print(f'strides  = {arr1.strides}') # (행이동 메모리칸수, 열이동 메모리 칸수)

[[11 22 33]]
shape    = (1, 3)
ndim     = 2
dtype    = int16
itemsize = 2
data     = <memory at 0x000001FF7E2FAA80>
strides  = (6, 2)


In [8]:
# [방법2] 특정값으로 채운 ndarray 생성
# np.zeros()
arr1 = np.zeros((3,))
arr2 = np.zeros((2,4))
arr3 = np.zeros((2,4), dtype=np.int8)

print(arr1)
print(arr2)
print(arr3)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]]


In [9]:
# np.ones() : 모든 원소값 1인 배열 객체
arr1 = np.ones(3)
arr2 = np.ones((3,2))
arr3 = np.ones((3,2), dtype=np.bool)

print(arr1)
print(arr2)
print(arr3)

[1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [10]:
# np.full() : 원하는 특정 값으로 채운 배열 객체
arr1 = np.full((2,3), 7)
arr1

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
base = np.array([[11,22,33],[44,55,66]])
arr1 = np.zeros_like(base)
arr2 = np.ones_like(base)
arr3 = np.full_like(base,5)
print(arr1,arr2,arr3 , sep="\n\n")

[[0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]]

[[5 5 5]
 [5 5 5]]


In [ ]:
# np.eye() : 대각선 1로 채운 array : np.eye() <--- 2D array 생성
arr1 = np.eye(5)
arr2 = np.eye(5,3)

print(arr1, arr2, sep="\n\n")

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# np.diag() : 대각선 특정값으로 채운 array
arr1 = np.diag([3,5,7])
arr2 = np.diag([[3,5,7], [2,4,6]]) # 대각선에 해당하는 값으로 채운 array

print(arr1, arr2, sep="\n\n")

[[3 0 0]
 [0 5 0]
 [0 0 7]]

[3 4]


In [ ]:
# [방법3] 범위 지정해서 ndarray 생성
# => np.arange()
arr1 = np.arange(5)

# => np.linspace()
arr2, step = np.linspace(0, 5, retstep=True, num=6)

# => np.logspace()
arr3 = np.logspace(0, 5, num=6)

print("arr1", arr1, sep='\n')
print("arr2", step, arr2, sep='\n')
print("arr3", arr3, sep='\n')

arr1
[0 1 2 3 4]
arr2
1.0
[0. 1. 2. 3. 4. 5.]
arr3
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [ ]:
# [방법4] 특정 형태의 배열 객체 생성. 초기화 안됨(기존의 데이터들)값 존재
arr1 = np.empty((3,2))

arr2 = np.empty_like(arr1)
arr2

array([[1.e+00, 1.e+01],
       [1.e+02, 1.e+03],
       [1.e+04, 1.e+05]])