## [ Numpy - ndarray 원소 접근] 
<hr>

- 인덱싱 기반 : 왼 -> 오, 오 -> 왼 2개 종류 인덱스
- 슬라이싱 : 연속적이거나 일정한 규칙이 있는 원소 접근 방식

In [1]:
# 모듈 로딩
import numpy as np
import pandas as pd

In [ ]:
# 실습 데이터 생성
data = np.arange(2, 20, 3)
data

array([ 2,  5,  8, 11, 14, 17])

In [7]:
# ndarray 원소 접근 - 인덱싱
print(data[0], type(data[0]), data[0].ndim)
print(data[-1], type(data[-1]), data[-1].ndim)

2 <class 'numpy.int64'> 0
17 <class 'numpy.int64'> 0


In [9]:
# 원소값 변경
data[0] = 99
print(data)

[99  5  8 11 14 17]


In [11]:
# ndarray 원소 접근 - 슬라이싱
data[0:-2]

array([99,  5,  8, 11])

In [ ]:
# 슬라이싱 + 값 변경
# View 타입 : 값 변경 시 원본 데이터 변경 됨
data[0:-3] = 7

# copy 타입 : 복사본 즉, 메모리 새롭게 저장, 값 변경 시 원본 데이터 변경 X
data2 = data[0:3].copy()
data2[0:-1] = 9

print(data, data2, sep='\n')

[ 7  7  7 11 14 17]
[9 9 7]


### [ Numpy Fancy Indexing ] <hr>
- 원하는 데이터의 인덱스를 배열/리스트에 담아서 한꺼번에 추출하는 인덱싱
- 예 : 배열명[[인덱스, 인덱스]]

In [ ]:
import numpy as np

In [ ]:
dataNP = np.array([[11,22,33], [44,55,66]], dtype=np.int8)

In [ ]:
# 팬시 인덱싱 => 2번, 0번 컬럼 추출 
dataNP[:, [2,0]] = 9
dataNP

array([[ 9, 22,  9],
       [ 9, 55,  9]], dtype=int8)

In [ ]:
# 팬시 인덱싱 => 1번, 0번 컬럼 추출 
dataNP2 = dataNP[[1,0]]
dataNP2

array([[ 9, 55,  9],
       [ 9, 22,  9]], dtype=int8)