### [ Numpy shape 변환 ] <hr>
- 1차원 < - - - > N 차원 변환
- 배열의 형태 변환
- np.함수명() / ndarray.메서드명()
    * reshape() / flatten() / ravel()

In [1]:
import numpy as np

In [58]:
dataNP = np.array([[11,22,33], [44,55,66]], dtype=np.int8)

In [ ]:
# shape 변환 [1] reshape() : N차원으로 변환. View 타입으로 데이터 공유. *원소 개수 동일
print(f'dataNP 변환 전 shape : {dataNP.shape}')

newNP1 = dataNP.reshape(1,6) # 2D (1,6)
newNP2 = dataNP.reshape(-1)  # -1의미 : 알아서 해줘. 1차원으로 변환해줘.

print(f'dataNP 변환 후 shape : {dataNP.shape}')
print(f'newNP1 shape : {newNP1.shape}')
print(f'newNP2 shape : {newNP2.shape}')


dataNP 변환 전 shape : (2, 3)
dataNP 변환 후 shape : (2, 3)
newNP1 shape : (1, 6)
newNP2 shape : (6,)


In [60]:
print(f'dataNP 변환 전 shape : {dataNP.shape}')

newNP1 = dataNP.reshape((-1,1)) # 2D (-1,1) : 컬럼 1개인 형태로 변환. 행은 알아서 계산
                                #             단, 변환 전 후 원소 개수 동일해야함.

print(f'dataNP 변환 후 shape : {dataNP.shape}')
print(f'newNP1 shape : {newNP1.shape}')
newNP1

dataNP 변환 전 shape : (2, 3)
dataNP 변환 후 shape : (2, 3)
newNP1 shape : (6, 1)


array([[11],
       [22],
       [33],
       [44],
       [55],
       [66]], dtype=int8)

In [61]:
print(f'dataNP 변환 전 shape : {dataNP.shape}')

newNP1 = dataNP.reshape((3,-1,1)) # 3D (-1,1) : 컬럼 1개인 형태로 변환. 행은 알아서 계산
                                  #             단, 변환 전 후 원소 개수 동일해야함.

print(f'dataNP 변환 후 shape : {dataNP.shape}')
print(f'newNP1 shape : {newNP1.shape}')
newNP1

dataNP 변환 전 shape : (2, 3)
dataNP 변환 후 shape : (2, 3)
newNP1 shape : (3, 2, 1)


array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]], dtype=int8)

In [62]:
# ndarray의 원소값 변경 전 후 비교
# reshape() 메서드 => view타입의 ndarray 반환. 즉, 데이터가 공유됨
dataNP[1][1] = 7
print(dataNP, newNP1, sep='\n')
print(f'{id(dataNP)}, {id(newNP1)}, {id(dataNP[1][1])}')

[[11 22 33]
 [44  7 66]]
[[[11]
  [22]]

 [[33]
  [44]]

 [[ 7]
  [66]]]
2133005322640, 2133028715472, 2133004595664


In [64]:
# shape 변환 [2] flatten(): 1D ndarray, 데이터 복사함!
newNP1 = dataNP.flatten()

print(f'dataNP : {dataNP.shape}, newNP1 : {newNP1.shape}')

# 원소 변경 후 비교
dataNP[0][-1] = 100
print(f'dataNP :\n{dataNP}, \nnewNP1 : {newNP1}')

dataNP : (2, 3), newNP1 : (6,)
dataNP :
[[ 11  22 100]
 [ 44   7  66]], 
newNP1 : [ 11  22 100  44   7  66]


In [ ]:
# shape 변환 [3] reval(): 1D array 반환. View 타입으로 데이터 공유됨.
newNP1 = dataNP.ravel()

print(f'dataNP : {dataNP.shape}, newNP1 : {newNP1.shape}')

# 원소 변경 후 비교
dataNP[0][-1] = 1
print(f'dataNP :\n{dataNP}, \nnewNP1 : {newNP1}')

dataNP : (2, 3), newNP1 : (6,)
dataNP :
[[11 22  1]
 [44  7 66]], 
newNP1 : [11 22  1 44  7 66]


In [70]:
# 함수와 메서드 차이
# np.함수명()
np.reshape(dataNP,(3,2))
# np.ravel()

# ndarray.메서드명()
dataNP.reshape((6,1,1))
# dataNP.ravel()

array([[[11]],

       [[22]],

       [[ 1]],

       [[44]],

       [[ 7]],

       [[66]]], dtype=int8)

### [ Numpy Axes 변환 ] <hr>
- 차원, 원소 개수 유지
- 축 변경
- shape 속성에서 확인 => ndarray.shape => (행, 열), (깊이, 행, 열)

In [ ]:
import numpy as np

In [ ]:
dataNP = np.arange(24).reshape((1,3,2,4))
dataNP

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [ ]:
# 축 변환 [1] 속성.T : 원본 유지, 변환된 축의 새로운 ndarray 반환
print(f'dataNP 변환 전 shape : {dataNP.shape}, {dataNP.T.shape}')

dataNP 변환 전 shape : (1, 3, 2, 4), (4, 2, 3, 1)


In [ ]:
# 축 변환 [2] ndarray.swapaxes(축1, 축2) : 원본 유지, 2개 축 변환한 새로운 ndarray 반환
newNP = dataNP.swapaxes(0,3) # 0번축과 3번축 변경
print(f'dataNP 변환 전 shape : {dataNP.shape}, newNP의 shape : {newNP.shape}')

dataNP 변환 전 shape : (1, 3, 2, 4), newNP의 shape : (4, 3, 2, 1)


In [ ]:
# 축 변환 [3] ndarray.transpose() : 원본 유지, 축 변환한 새로운 ndarray 반환
# 현재 shape => (1,3,2,4) : 축의 인덱스 즉, 0, 1, 2, 3
newNP = dataNP.transpose(1,3,0,2) # 전체 축 설정
print(f'dataNP 변환 전 shape : {dataNP.shape}, newNP의 shape : {newNP.shape}')

dataNP 변환 전 shape : (1, 3, 2, 4), newNP의 shape : (3, 4, 1, 2)
