### [Full Connected Layer - Linear Layer]
- 모든 뉴런들이 다음 층의 뉴런들과 연결되는 중
- Pytorch에서는 Linear 클래스로 규현되어 있음
- 피쳐와 가중치 곱셈 + 절현 연산 수행

- torch.nn.Linear 클래스
    * 주요 매개변수 : 입력 개수와 출력 개수
    * 해당 총에 퍼셉트론 생성 <= 출력 개수>
    * w, B 텐서 생성 및 초가화(랜덤)
    * 순전파 진행 후 결과 반환

In [1]:
import torch
import torch.nn as nn # 인공신경망 관련 모듈

>> Linear 클래스 이해하기

In [6]:
# 입력과 출력 선정
in_, out_ = 5, 10

# Linear 인스턴스 생성
# => w, b 텐서 생성 및 초기화(랜덤)
llayer = nn.Linear(in_, out_)

In [7]:
print(llayer.weight)
print(llayer.bias)

Parameter containing:
tensor([[-0.2123, -0.2380, -0.2277,  0.0382, -0.2190],
        [-0.2526,  0.0281,  0.1602,  0.4106, -0.1284],
        [ 0.0906, -0.2835, -0.3635,  0.2751, -0.1193],
        [-0.0311, -0.3123,  0.4228, -0.3558,  0.3864],
        [-0.2272, -0.2059, -0.2569,  0.4454,  0.2896],
        [ 0.1436, -0.2313, -0.3712, -0.3780,  0.2076],
        [-0.2975,  0.2074,  0.1540,  0.3625, -0.0621],
        [ 0.0263,  0.2593, -0.3064, -0.0460,  0.2944],
        [-0.3750, -0.1327, -0.3351,  0.1171, -0.4101],
        [ 0.1023,  0.1449,  0.1081,  0.1114,  0.0854]], requires_grad=True)
Parameter containing:
tensor([ 0.3780,  0.1661, -0.2476, -0.0582, -0.4122,  0.0760,  0.1634,  0.3968,
        -0.2043, -0.2701], requires_grad=True)


In [12]:
# 순전파(Forward) 진행 : 변수명( 입력 데이터 )
# data = torch.tensor([[11,22,33,44,55]], dtype=torch.float32)
data = torch.FloatTensor([[11,22,33,44,55]])
llayer(data)

tensor([[-25.0686,  14.3001, -11.9357,  12.2782,  19.6080, -20.8967,  19.0702,
          10.4486, -35.7111,  17.2110]], grad_fn=<AddmmBackward0>)